### ISSUE TITLE
Unable to troubleshoot S3 connector issues

### ISSUE THREAD

**Issue by caseyTMcoke** [TurnUpTheBass/axway-b2bi-plugins#1]
Unable to determine cause when things aren't working.  Apparently there should be logging that can be reviewed by Axway cloud support team as to the reason for failure.
<img width="782" alt="S3Error" src="https://user-images.githubusercontent.com/55515791/65192746-43b4d080-da46-11e9-9349-d3339ed0f029.PNG">
<img width="782" alt="S3Error" src="https://user-images.githubusercontent.com/55515791/65192756-4a434800-da46-11e9-9152-e0a8daba45b1.PNG">

**Comment by TurnUpTheBass** [comment]
With debugging turned on, additional details should appear. The reported issue was due to nested folder structures - this has been corrected.

**Comment by TurnUpTheBass** [comment]
With debugging turned on, additional details should appear. The reported issue was due to nested folder structures - this has been corrected.
